/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package f1;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author tanishj52
 */
public class imagePanel extends javax.swing.JPanel {

    private Image backgroundImage;
    /**
     * Creates new form imagePanel
     */
    public imagePanel() {
        // Load the image from the resources folder
        // IMPORTANT: Replace "f1/images/bg.jpeg" with the correct path to your image
        try {
            // Using getResource ensures the image is found when the application is built
            backgroundImage = new ImageIcon(getClass().getResource("/f1/images/bg.jpeg")).getImage();
        } catch (Exception e) {
            System.err.println("Could not load background image: " + e.getMessage());
            // Optionally set a default color if image fails to load
            setBackground(java.awt.Color.LIGHT_GRAY); 
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Clears the background

        if (backgroundImage != null) {
            // Draw the image, scaling it to fit the panel size
            g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
