/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package f1;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author tanishj52
 */
public class Profile extends JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());

    private String userName;
    private String userHeight;
    private String userWeight;
    /**
     * Creates new form ProfileDialog
     */
    public Profile(JFrame owner, String name, String height, String weight) {
        super(owner, "User Profile", true); 
        this.userName = name;
        this.userHeight = height;
        this.userWeight = weight;
        
        setupDialogUI();
    }
    
    private void setupDialogUI() {
        setSize(300, 250);
        setLocationRelativeTo(getOwner()); 
        setLayout(new GridBagLayout());
        getContentPane().setBackground(Color.WHITE); 

        Font labelFont = new Font("SansSerif", Font.BOLD, 14);
        Font valueFont = new Font("SansSerif", Font.PLAIN, 14);
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;
        
        // Title
        JLabel title = new JLabel("Your Profile Details");
        title.setFont(new Font("SansSerif", Font.BOLD, 18));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        add(title, gbc);
        
        gbc.gridwidth = 1;
        gbc.anchor = GridBagConstraints.WEST; // Reset alignment for form fields

        // 1. Name
        JLabel nameLbl = new JLabel("Name:");
        nameLbl.setFont(labelFont);
        gbc.gridx = 0; gbc.gridy = 1;
        add(nameLbl, gbc);
        
        JLabel nameVal = new JLabel(userName);
        nameVal.setFont(valueFont);
        gbc.gridx = 1; gbc.gridy = 1;
        add(nameVal, gbc);

        // 2. Height
        JLabel heightLbl = new JLabel("Height:");
        heightLbl.setFont(labelFont);
        gbc.gridx = 0; gbc.gridy = 2;
        add(heightLbl, gbc);

        JLabel heightVal = new JLabel(userHeight);
        heightVal.setFont(valueFont);
        gbc.gridx = 1; gbc.gridy = 2;
        add(heightVal, gbc);

        // 3. Weight
        JLabel weightLbl = new JLabel("Weight:");
        weightLbl.setFont(labelFont);
        gbc.gridx = 0; gbc.gridy = 3;
        add(weightLbl, gbc);

        JLabel weightVal = new JLabel(userWeight);
        weightVal.setFont(valueFont);
        gbc.gridx = 1; gbc.gridy = 3;
        add(weightVal, gbc);
        
        pack(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Profile dialog = new Profile(null, "Tanish", "175 cm", "75 kg");
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
