/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package f1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanishj52
 */
public class viewMeals extends JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewMeals.class.getName());

    private JTable mealTable;
    private DefaultTableModel tableModel;
    private JButton closeButton;
    
    private final String[] COLUMN_NAMES = {"Meal", "Calories", "Date"};
    /**
     * Creates new form viewMeals
     * @param owner
     */
    public viewMeals(JFrame owner) {
        super(owner, "View Recorded Meals", true); 
        setupDialogUI();
         loadMeals();
    }
    
    private void setupDialogUI() {
        setSize(550, 400);
        setLocationRelativeTo(getOwner()); 
        setLayout(new BorderLayout(10, 10)); 

        Font sansSerifBold = new Font("SansSerif", Font.BOLD, 14);
        
        tableModel = new DefaultTableModel(COLUMN_NAMES, 0); 
        mealTable = new JTable(tableModel);
        
        mealTable.getTableHeader().setFont(sansSerifBold);
        mealTable.getTableHeader().setBackground(new Color(70, 130, 180)); 
        mealTable.getTableHeader().setForeground(Color.WHITE);
        mealTable.setFont(new Font("SansSerif", Font.PLAIN, 12));
        mealTable.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(mealTable);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 10)); 
        
        add(scrollPane, BorderLayout.CENTER);

        closeButton = new JButton("Close");
        closeButton.setFont(sansSerifBold);
        closeButton.setPreferredSize(new Dimension(100, 30));
        closeButton.setBackground(new Color(220, 20, 60)); 
        closeButton.setForeground(Color.WHITE);
        closeButton.setFocusPainted(false);
        
        closeButton.addActionListener(e -> dispose()); 

        JPanel southPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        southPanel.add(closeButton);
        add(southPanel, BorderLayout.SOUTH);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    private void loadMeals() {
    tableModel.setRowCount(0); 
    String sql = "SELECT * FROM meals";
    try (Connection conn = db.DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] row = new Object[3];
            row[0] = rs.getString("meal_name");
            row[1] = rs.getInt("calories");
            row[2] = rs.getString("date");
            tableModel.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        viewMeals dialog = new viewMeals(null);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
