/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package f1;

import static java.awt.AWTEventMulticaster.add;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanishj52
 */
public class viewWorkout extends JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewWorkout.class.getName());
    private JTable workoutTable;
    private DefaultTableModel tableModel;
    private JButton closeButton;
    private final String[] COLUMN_NAMES = {"Workout", "Time", "Calories Burned", "Date"};
    /**
     * Creates new form viewWorkout
     */
    public viewWorkout(JFrame owner) {
        super(owner, "View Recorded Workouts", true); // true makes it modal
        setupDialogUI();
        // Load example data after UI is set up
//        loadExampleData(); 
    }
    
    private void setupDialogUI() {
        setSize(650, 450); 
        setLocationRelativeTo(getOwner()); 
        setLayout(new BorderLayout(10, 10));

        Font sansSerifBold = new Font("SansSerif", Font.BOLD, 14);
        
        tableModel = new DefaultTableModel(COLUMN_NAMES, 0); 
        workoutTable = new JTable(tableModel);
        
        workoutTable.getTableHeader().setFont(sansSerifBold);
        workoutTable.getTableHeader().setBackground(new Color(70, 130, 180));
        workoutTable.getTableHeader().setForeground(Color.WHITE);
        workoutTable.setFont(new Font("SansSerif", Font.PLAIN, 12));
        workoutTable.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(workoutTable);
        scrollPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 0, 10)); 
        
        add(scrollPane, BorderLayout.CENTER);

        closeButton = new JButton("Close");
        closeButton.setFont(sansSerifBold);
        closeButton.setPreferredSize(new Dimension(100, 30));
        closeButton.setBackground(new Color(220, 20, 60));
        closeButton.setForeground(Color.WHITE);
        closeButton.setFocusPainted(false);
        
        closeButton.addActionListener(e -> dispose()); 

        JPanel southPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        southPanel.add(closeButton);
        add(southPanel, BorderLayout.SOUTH);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    /**
     * This method simulates loading data. In a real app, this would query a database.
     */
    private void loadExampleData() {
        // Clear existing data
        tableModel.setRowCount(0); 
        
        // Example workout data
        Object[][] data = {
            {"Running", "45 mins", "400", "26/10/2025"},
            {"Weight Lifting", "60 mins", "350", "26/10/2025"},
            {"Yoga", "30 mins", "150", "25/10/2025"},
            {"Cycling", "90 mins", "700", "24/10/2025"}
        };
        
        // Add data to the table model
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        viewWorkout dialog = new viewWorkout(null);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
